[project]
name = "clickhouse-connector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "clickhouse-connect>=0.8.18",
    "dotenv>=0.9.9",
    "pytest>=8.4.1",
]
